import { env } from "@my-better-t-app/env/server";

interface TranscriptionResult {
  text: string;
  confidence?: number;
}

export async function transcribeAudio(audioBuffer: Buffer): Promise<TranscriptionResult> {
  if (env.TRANSCRIPTION_SERVICE === "openai") {
    return transcribeWithOpenAI(audioBuffer);
  } else {
    return transcribeLocally(audioBuffer);
  }
}

async function transcribeWithOpenAI(audioBuffer: Buffer): Promise<TranscriptionResult> {
  if (!env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY not set");
  }

  const formData = new FormData();
  const blob = new Blob([audioBuffer], { type: "audio/wav" });
  formData.append("file", blob, "audio.wav");
  formData.append("model", "whisper-1");
  formData.append("language", "en");

  const response = await fetch("https://api.openai.com/v1/audio/transcriptions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${env.OPENAI_API_KEY}`,
    },
    body: formData,
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.statusText}`);
  }

  const result = (await response.json()) as { text: string };
  return { text: result.text };
}

async function transcribeLocally(audioBuffer: Buffer): Promise<TranscriptionResult> {
  // Local transcription stub - replace with actual local transcription service
  // For now, returns a placeholder
  // You can integrate with services like:
  // - Vosk for local speech recognition
  // - Mozilla STT
  // - AssemblyAI
  
  console.log(
    "Local transcription requested for buffer of size:",
    audioBuffer.length
  );

  // Simulate async transcription
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        text: "[Transcription would be generated by local service]",
        confidence: 0.8,
      });
    }, 100);
  });
}
